stages:
  - build

before_script:
  - echo "Start CI/CD building"

build-gradle:
  image: openjdk:11
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

after_script:
  - echo "End CI/CD build"