stages:
  - buildFE
  - buildBE
  - testBE

before_script:
  - echo "Start CI/CD building"
build-gradle:
  image: openjdk:16
  stage: buildFE
  script:
    - cd client
    - chmod +x ./gradlew 
    - ./gradlew assemble --scan
    - cd ..
  artifacts:
    paths:
      - build/libs/*.jar

build-gradleBE:
  image: openjdk:16
  stage: buildBE
  script:
    - cd server 
    - chmod +x ./gradlew 
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar

test-BE:
  image: openjdk:16
  stage: testBE
  script:
    - cd server 
    - chmod +x ./gradlew 
    - ./gradlew check

after_script:
  - echo "End CI/CD build"
