###
GET localhost:8081/players

###
POST localhost:8081/players
Content-Type: application/json

{
  "firstName": "Bo",
  "secondName": "Bichette",
  "baseballPosition": "ShortStop",
  "dateOfBirth": "5.3.1998"
}

###
POST localhost:8081/players
Content-Type: application/json

{
"firstName": "Vladimir",
"secondName": "Guerrero jr.",
"baseballPosition": "FirstBase",
"dateOfBirth": "16.3.1999",
"teamID": "15"
}

###
DELETE localhost:8080/players/17

