###
POST http://localhost:8080/PlayerAward/addingPlayerAward
Content-Type: application/json

{
  "awardID": "3",
  "playerID": "17"
}

###
POST http://localhost:8080/PlayerAward/addingPlayerAward
Content-Type: application/json

{
  "awardID": "13",
  "playerID": "16"
}

###
DELETE http://localhost:8080/PlayerAward/deletePlayer/17
Content-Type: application/json

{
  "awardID": "3",
  "playerID": "17"
}

###
DELETE http://localhost:8081/PlayerAward/deletePlayer/3
Content-Type: application/json

{
  "awardID": "3",
  "playerID": "17"
}