###
GET localhost:8080/teams

###
POST localhost:8080/teams
Content-Type: application/json

{
	"name":"Los Angels  Dodgers",
	"league":"NationalLeague",
	"yearOfEstablish":"1890",
	"numOfWorldSeriesWin":"7"

}

###
POST localhost:8080/teams
Content-Type: application/json

{
  "name":"Toronto Blue Jays",
  "league":"AmericanLeague",
  "yearOfEstablish":"1972",
  "numOfWorldSeriesWin":"2"

}

###
POST localhost:8080/teams
Content-Type: application/json

{
  "name":"Toronto Blue Jays",
  "league":"AmericanLeague",
  "yearOfEstablish":"1972",
  "numOfWorldSeriesWin":"2"

}

###
POST localhost:8080/teams
Content-Type: application/json

{
  "name":"Atlanta Braves",
  "league":"NationalLeague",
  "yearOfEstablish":"1876",
  "numOfWorldSeriesWin":"3"

}

###
GET localhost:8080/teams


###
DELETE localhost:8080/teams/53

###
GET localhost:8080/teams

###
PUT localhost:8080/teams/14
Content-Type: application/json

{
  "name":"Atlanta Braves",
  "league":"NationalLeague",
  "yearOfEstablish":"1876",
  "numOfWorldSeriesWin":"4"

}



###
GET localhost:8080/teams